import "./channel-config-helpers-DXyHWBVJ.js";
import { Ii as buildOllamaProvider, Li as buildSglangProvider, Ri as buildVllmProvider, co as loadSecretFileSync, lo as readSecretFileSync, so as DEFAULT_SECRET_FILE_MAX_BYTES, uo as tryReadSecretFileSync, zi as OLLAMA_DEFAULT_BASE_URL } from "./thread-bindings-0Uc4GeBT.js";
import "./paths-WR8OhEmw.js";
import "./github-copilot-token-BGYH4ltJ.js";
import "./logger-C9fkmDdb.js";
import { t as resolvePreferredOpenClawTmpDir } from "./tmp-openclaw-dir-DRPiOszV.js";
import "./globals-DMfGJ_36.js";
import "./utils-DfdxfpoM.js";
import "./subsystem-CfLo2GBS.js";
import "./fetch-DftkrN27.js";
import "./exec-Btxwbj1p.js";
import "./thinking-CSUA5PYQ.js";
import "./query-expansion-s2jldUV4.js";
import "./logger-BYeF241k.js";
import "./zod-schema.core-De203jOD.js";
import "./redact-BuzJ8kUo.js";
import "./http-registry-BsB8N5w2.js";
import "./pairing-token-DX0HaDzb.js";
import "./ssrf--5Fh_apX.js";
import "./fetch-guard-B43Ufsg7.js";
import "./registry-SHl7cuYc.js";
import "./http-body-Cgn9Rlev.js";
import { t as emptyPluginConfigSchema } from "./config-schema-CSqB9hID.js";
import "./provider-env-vars-CYpJ3fRA.js";
import { t as buildOauthProviderAuthResult } from "./provider-auth-result-CFMpuanF.js";
import { t as runPluginCommandWithTimeout } from "./run-command-C5Jo3Wgr.js";
import { a as resolveGatewayBindUrl, i as resolveTailnetHostWithRunner, n as listDevicePairing, r as rejectDevicePairing, t as approveDevicePairing } from "./device-pairing-BHSGMREN.js";
import { _ as promptAndConfigureOpenAICompatibleSelfHostedProviderAuth, a as promptAndConfigureVllm, c as ensureOllamaModelPulled, d as SELF_HOSTED_DEFAULT_COST, f as SELF_HOSTED_DEFAULT_MAX_TOKENS, g as promptAndConfigureOpenAICompatibleSelfHostedProvider, h as discoverOpenAICompatibleSelfHostedProvider, i as VLLM_DEFAULT_MAX_TOKENS, l as promptAndConfigureOllama, m as configureOpenAICompatibleSelfHostedProviderNonInteractive, n as VLLM_DEFAULT_CONTEXT_WINDOW, o as OLLAMA_DEFAULT_MODEL, p as applyProviderDefaultModel, r as VLLM_DEFAULT_COST, s as configureOllamaNonInteractive, t as VLLM_DEFAULT_BASE_URL, u as SELF_HOSTED_DEFAULT_CONTEXT_WINDOW } from "./vllm-setup-BZv8_7Bz.js";
export { DEFAULT_SECRET_FILE_MAX_BYTES, OLLAMA_DEFAULT_BASE_URL, OLLAMA_DEFAULT_MODEL, SELF_HOSTED_DEFAULT_CONTEXT_WINDOW, SELF_HOSTED_DEFAULT_COST, SELF_HOSTED_DEFAULT_MAX_TOKENS, VLLM_DEFAULT_BASE_URL, VLLM_DEFAULT_CONTEXT_WINDOW, VLLM_DEFAULT_COST, VLLM_DEFAULT_MAX_TOKENS, applyProviderDefaultModel, approveDevicePairing, buildOauthProviderAuthResult, buildOllamaProvider, buildSglangProvider, buildVllmProvider, configureOllamaNonInteractive, configureOpenAICompatibleSelfHostedProviderNonInteractive, discoverOpenAICompatibleSelfHostedProvider, emptyPluginConfigSchema, ensureOllamaModelPulled, listDevicePairing, loadSecretFileSync, promptAndConfigureOllama, promptAndConfigureOpenAICompatibleSelfHostedProvider, promptAndConfigureOpenAICompatibleSelfHostedProviderAuth, promptAndConfigureVllm, readSecretFileSync, rejectDevicePairing, resolveGatewayBindUrl, resolvePreferredOpenClawTmpDir, resolveTailnetHostWithRunner, runPluginCommandWithTimeout, tryReadSecretFileSync };
